import { Component } from '@angular/core';
import { IonApp, IonRouterOutlet,  } from '@ionic/angular/standalone';
import { Router } from '@angular/router';
import { MenuController, } from '@ionic/angular';
import { addIcons } from 'ionicons';
import {
  
  personCircleOutline,
  homeOutline,
  settingsOutline,
  logOutOutline,
  menuOutline,
  closeOutline,
  addOutline,
  trashOutline,
  createOutline,
  searchOutline,
  chevronForwardOutline,
  chevronBackOutline,
  locationOutline,
  callOutline,
  mailOutline,
  peopleOutline,
  checkmarkDoneOutline,
  calendarOutline,
  ellipseOutline,
  arrowBack,
  playCircle,
  navigate,
  navigateCircle,
  time,
  storefrontOutline,
  cashOutline,
  checkmarkCircle,
  playSkipForward,
  chevronForward,
  close,
  saveOutline,
  add,
  remove,
  car,
  star,
  eyeOutline,
  warningOutline,
  waterOutline,
  volumeHigh,
  flag,
  volumeMute,
  pauseCircle,
  downloadOutline,
  document,
  folderOpen,
  documentText,
  clipboardOutline,
  closeCircle,
  listOutline,
  chevronDown,
  pricetag,
  lockClosed,
  alertCircle,
  checkmark,
  bicycleOutline,
  cloudUploadOutline,
  card,
  save,
  chevronUp,
  mapOutline,
  arrowBackOutline,
  fingerPrint,
  location,
  checkmarkCircleOutline,
  alertCircleOutline,
  list,
  calculatorOutline,
  informationCircle,
  personOutline
} from 'ionicons/icons';

@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html',
  imports: [ IonApp, IonRouterOutlet, ],
  
})
export class AppComponent {
 constructor(private readonly menu: MenuController, private readonly router: Router) {
  addIcons({
    'checkmark-circle-outline': checkmarkCircleOutline,
  'person-circle-outline': personCircleOutline,
  'home-outline': homeOutline,
  'settings-outline': settingsOutline,
  'log-out-outline': logOutOutline,
  'menu-outline': menuOutline,
  'close-outline': closeOutline,
  'add-outline': addOutline,
  'trash-outline': trashOutline,
  'create-outline': createOutline,
  'search-outline': searchOutline,
  'chevron-forward-outline': chevronForwardOutline,
  'chevron-back-outline': chevronBackOutline,
  'location-outline': locationOutline,
  'call-outline': callOutline,
  'mail-outline': mailOutline,
  'people-outline': peopleOutline,
  'checkmark-done-outline': checkmarkDoneOutline,
  'calendar-outline': calendarOutline,
  'ellipse-outline': ellipseOutline,
  'arrow-back':arrowBack,
  'play-circle':playCircle,
  'navigate':navigate,
  'person-outline':personOutline,
  'navigate-circle':navigateCircle,
  'time':time,
  'storefront-outline':storefrontOutline,
  'cash-outline':cashOutline,
  'checkmark-circle': checkmarkCircle,
  'play-skip-forward': playSkipForward,
  'chevron-forward':chevronForward,
  'close':close,
  'save-outline':saveOutline,
  'add':add,
  'remove':remove,
  'car':car,
  'eye-outline': eyeOutline,
  'warning-outline': warningOutline,
  'water-outline': waterOutline,
  'volume-high': volumeHigh,
  'flag':flag,
  'finger-print': fingerPrint,
  'volume-mute':volumeMute,
  'pause-circle': pauseCircle,
  'download-outline': downloadOutline,
  'document': document,
  'folder-open': folderOpen,
  'document-text': documentText,
  'clipboard-outline': clipboardOutline,
  'close-circle': closeCircle,
  'list-outline': listOutline,
  'chevron-down': chevronDown,
  'pricetag': pricetag,
  'lock-closed': lockClosed,
  'alert-circle': alertCircle,
  'checkmark': checkmark,
  'bicycle-outline': bicycleOutline,
  'cloud-upload-outline': cloudUploadOutline,
  'card': card,
  'save': save,
  'chevron-up': chevronUp,
  'map-outline': mapOutline,
  'arrow-back-outline': arrowBackOutline,
  'location': location,
  'alert-circle-outline': alertCircleOutline,
  'list': list,
  'calculator-outline': calculatorOutline,
  'information-circle': informationCircle,
});
 }


}
